# Generated by Django 4.1.4 on 2023-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
    ]
